//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class easymissionContext : DbContext
    {
        public easymissionContext()
            : base("name=easymissionContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<candidature> candidatures { get; set; }
        public DbSet<forum> fora { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<promotion> promotions { get; set; }
        public DbSet<reclamation> reclamations { get; set; }
        public DbSet<service> services { get; set; }
        public DbSet<sujet> sujets { get; set; }
        public DbSet<user> users { get; set; }
    }
}
