//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public promotion()
        {
            this.services = new HashSet<service>();
        }
    
        public int idPromotion { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public string description { get; set; }
        public Nullable<int> user_idUser { get; set; }
    
        public virtual ICollection<service> services { get; set; }
        public virtual user user { get; set; }
    }
}
