//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int idService { get; set; }
        public string categorieService { get; set; }
        public string nomService { get; set; }
        public Nullable<int> payment_idPayment { get; set; }
        public Nullable<int> promotion_idPromotion { get; set; }
        public Nullable<int> user_idUser { get; set; }
    
        public virtual payment payment { get; set; }
        public virtual promotion promotion { get; set; }
        public virtual user user { get; set; }
    }
}
