//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.candidatures = new HashSet<candidature>();
            this.payments = new HashSet<payment>();
            this.promotions = new HashSet<promotion>();
            this.reclamations = new HashSet<reclamation>();
            this.services = new HashSet<service>();
            this.sujets = new HashSet<sujet>();
        }
    
        public int idUser { get; set; }
        public string competence { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public string login { get; set; }
        public string nom { get; set; }
        public string password { get; set; }
        public string prenom { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<candidature> candidatures { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<promotion> promotions { get; set; }
        public virtual ICollection<reclamation> reclamations { get; set; }
        public virtual ICollection<service> services { get; set; }
        public virtual ICollection<sujet> sujets { get; set; }
    }
}
