//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domaine
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnetuser
    {
        public aspnetuser()
        {
            this.aspnetuserclaims = new HashSet<aspnetuserclaim>();
            this.aspnetuserlogins = new HashSet<aspnetuserlogin>();
            this.cvs = new HashSet<cv>();
            this.candidatures = new HashSet<candidature>();
            this.commentaires = new HashSet<commentaire>();
            this.feedbacks = new HashSet<feedback>();
            this.cvs1 = new HashSet<cv>();
            this.reclamations = new HashSet<reclamation>();
            this.services = new HashSet<service>();
            this.promotions = new HashSet<promotion>();
            this.sujets = new HashSet<sujet>();
            this.offres = new HashSet<offre>();
            this.reclamations1 = new HashSet<reclamation>();
            this.aspnetroles = new HashSet<aspnetrole>();
            this.fora = new HashSet<forum>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Last_Name { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual ICollection<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual ICollection<cv> cvs { get; set; }
        public virtual ICollection<candidature> candidatures { get; set; }
        public virtual ICollection<commentaire> commentaires { get; set; }
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<cv> cvs1 { get; set; }
        public virtual ICollection<reclamation> reclamations { get; set; }
        public virtual ICollection<service> services { get; set; }
        public virtual ICollection<promotion> promotions { get; set; }
        public virtual ICollection<sujet> sujets { get; set; }
        public virtual ICollection<offre> offres { get; set; }
        public virtual ICollection<reclamation> reclamations1 { get; set; }
        public virtual ICollection<aspnetrole> aspnetroles { get; set; }
        public virtual ICollection<forum> fora { get; set; }
    }
}
