//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domaine
{
    using System;
    using System.Collections.Generic;
    
    public partial class forum
    {
        public forum()
        {
            this.commentaires = new HashSet<commentaire>();
            this.sujets = new HashSet<sujet>();
        }
    
        public int idForum { get; set; }
        public string nomForum { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> DateSubmit { get; set; }
        public string category { get; set; }
        public string idUser { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual ICollection<commentaire> commentaires { get; set; }
        public virtual ICollection<sujet> sujets { get; set; }
    }
}
