//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domaine
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int idPromotion { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public string description { get; set; }
        public string user_idUser { get; set; }
        public int idService { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual service service { get; set; }
    }
}
