//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domaine
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public service()
        {
            this.feedbacks = new HashSet<feedback>();
            this.offres = new HashSet<offre>();
            this.promotions = new HashSet<promotion>();
        }
    
        public int idService { get; set; }
        public string categorieService { get; set; }
        public string nomService { get; set; }
        public string user_idUser { get; set; }
        public string description { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<offre> offres { get; set; }
        public virtual ICollection<promotion> promotions { get; set; }
    }
}
