//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domaine
{
    using System;
    using System.Collections.Generic;
    
    public partial class sujet
    {
        public int idSujet { get; set; }
        public Nullable<System.DateTime> dateSujet { get; set; }
        public string description { get; set; }
        public string nomSujet { get; set; }
        public string typeSujet { get; set; }
        public Nullable<int> forum_idForum { get; set; }
        public string user_idUser { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual forum forum { get; set; }
    }
}
