//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMission.Domaine
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int idUser { get; set; }
        public string competence { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public string login { get; set; }
        public string nom { get; set; }
        public string password { get; set; }
        public string prenom { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<payment> payments { get; set; }
    }
}
